/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-03 03:50:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/home.css\">\r\n");
      out.write("    <title>음악의 시작, Band us</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <header class=\"bg-dark py-5\">\r\n");
      out.write("        <div class=\"container px-5\">\r\n");
      out.write("            <div class=\"row gx-5 justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"text-center my-5\">\r\n");
      out.write("                        <h1 class=\"display-5 fw-bolder text-white mb-2 cafe-text text-warning\">Band us</h1>\r\n");
      out.write("                        <h1 class=\"display-5 fw-bolder text-white mb-2 cafe-text\">처음이신가요?</h1>\r\n");
      out.write("                        <p class=\"lead text-white-50 mb-4\">'Band us'는 자신의 음악을 자유롭게 무료로 공유할 수 있는 커뮤니티입니다. 자신의 그룹을 만들어 친구들을 사귀고 서로의 음악을 공유할 수 있습니다. 이외에도 많은 기능이 있는데 가이드가 필요하신가요?</p>\r\n");
      out.write("                        <div class=\"d-grid gap-3 d-sm-flex justify-content-sm-center\">\r\n");
      out.write("                            <a class=\"btn btn-outline-warning px-4 me-sm-3\" href=\"#features\">더 알아보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Features section-->\r\n");
      out.write("    <section class=\"py-5 border-bottom\" id=\"features\">\r\n");
      out.write("        <div class=\"container px-5 my-5\">\r\n");
      out.write("            <div class=\"row gx-5\">\r\n");
      out.write("                <div class=\"col-lg-4 mb-5 mb-lg-0\" >\r\n");
      out.write("                <img src = \"img/home_1.jpg\" alt = \"home_1\" class = \"rounded\" width = \"330\" />\r\n");
      out.write("                   <div class=\"feature bg-primary bg-gradient text-white rounded-3 mb-3\"><i class=\"bi bi-collection\"></i></div>\r\n");
      out.write("                    <h2 class=\"h4 fw-bolder\">자신의 음악을 공유</h2>\r\n");
      out.write("                    <p>자신의 음악을 자유롭게 올리고 많은 사람들과 공유하세요! 가장 많은 조회수와 좋아요를 받은 음악은 랭크에 오릅니다! 좋은 곡을 올려 사람들에게 즐거움을 선사해주세요</p>\r\n");
      out.write("                    <a class=\"text-decoration-none\" href=\"#!\">\r\n");
      out.write("                        음악 공유하러가기\r\n");
      out.write("                        <i class=\"bi bi-arrow-right\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("                    <img src = \"img/home_2.jpg\" alt = \"home_1\" class = \"rounded\" width = \"330\" />\r\n");
      out.write("                    <div class=\"feature bg-primary bg-gradient text-white rounded-3 mb-3\"><i class=\"bi bi-building\"></i></div>\r\n");
      out.write("                    <h2 class=\"h4 fw-bolder\">성향이 맞는 친구 찾기</h2>\r\n");
      out.write("                    <p>Band us 는 친구들과 함께 활동할 수 있어요! 나의 친구가 어떤 음악을 좋아하고 어떤 성향을 가졌는지 알아볼까요?</p>\r\n");
      out.write("                    <a class=\"text-decoration-none\" href=\"#!\">\r\n");
      out.write("                        마이페이지로 이동\r\n");
      out.write("                        <i class=\"bi bi-arrow-right\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                <img src = \"img/home_3.jpg\" alt = \"home_1\" class = \"rounded\" width = \"330\" />\r\n");
      out.write("                    <div class=\"feature bg-primary bg-gradient text-white rounded-3 mb-3\"><i class=\"bi bi-toggles2\"></i></div>\r\n");
      out.write("                    <h2 class=\"h4 fw-bolder\">인기있는 음악 추천</h2>\r\n");
      out.write("                    <p>사람들은 어떤 노래를 좋아할까요? Band us에 올라온 노래 중 가장 많은 조회수와 인기를 얻은 곡을 확인할 수 있어요! 어쩌면 내 노래일지도..!?</p>\r\n");
      out.write("                    <a class=\"text-decoration-none\" href=\"#!\">\r\n");
      out.write("                        추천 노래 확인하러가기\r\n");
      out.write("                        <i class=\"bi bi-arrow-right\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Pricing section-->\r\n");
      out.write("    <section class=\"bg-light py-5 border-bottom\">\r\n");
      out.write("        <div class=\"container px-5 my-5\">\r\n");
      out.write("            <div class=\"text-center mb-5\">\r\n");
      out.write("                <h2 class=\"fw-bolder\">Pay as you grow</h2>\r\n");
      out.write("                <p class=\"lead mb-0\">With our no hassle pricing plans</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row gx-5 justify-content-center\">\r\n");
      out.write("                <!-- Pricing card free-->\r\n");
      out.write("                <div class=\"col-lg-6 col-xl-4\">\r\n");
      out.write("                    <div class=\"card mb-5 mb-xl-0\">\r\n");
      out.write("                        <div class=\"card-body p-5\">\r\n");
      out.write("                            <div class=\"small text-uppercase fw-bold text-muted\">Free</div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <span class=\"display-4 fw-bold\">$0</span>\r\n");
      out.write("                                <span class=\"text-muted\">/ mo.</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ul class=\"list-unstyled mb-4\">\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    <strong>1 users</strong>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    5GB storage\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Unlimited public projects\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Community access\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2 text-muted\">\r\n");
      out.write("                                    <i class=\"bi bi-x\"></i>\r\n");
      out.write("                                    Unlimited private projects\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2 text-muted\">\r\n");
      out.write("                                    <i class=\"bi bi-x\"></i>\r\n");
      out.write("                                    Dedicated support\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2 text-muted\">\r\n");
      out.write("                                    <i class=\"bi bi-x\"></i>\r\n");
      out.write("                                    Free linked domain\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"text-muted\">\r\n");
      out.write("                                    <i class=\"bi bi-x\"></i>\r\n");
      out.write("                                    Monthly status reports\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class=\"d-grid\"><a class=\"btn btn-outline-primary\" href=\"#!\">Choose plan</a></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Pricing card pro-->\r\n");
      out.write("                <div class=\"col-lg-6 col-xl-4\">\r\n");
      out.write("                    <div class=\"card mb-5 mb-xl-0\">\r\n");
      out.write("                        <div class=\"card-body p-5\">\r\n");
      out.write("                            <div class=\"small text-uppercase fw-bold\">\r\n");
      out.write("                                <i class=\"bi bi-star-fill text-warning\"></i>\r\n");
      out.write("                                Pro\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <span class=\"display-4 fw-bold\">$9</span>\r\n");
      out.write("                                <span class=\"text-muted\">/ mo.</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ul class=\"list-unstyled mb-4\">\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    <strong>5 users</strong>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    5GB storage\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Unlimited public projects\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Community access\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Unlimited private projects\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Dedicated support\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Free linked domain\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"text-muted\">\r\n");
      out.write("                                    <i class=\"bi bi-x\"></i>\r\n");
      out.write("                                    Monthly status reports\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class=\"d-grid\"><a class=\"btn btn-primary\" href=\"#!\">Choose plan</a></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Pricing card enterprise-->\r\n");
      out.write("                <div class=\"col-lg-6 col-xl-4\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body p-5\">\r\n");
      out.write("                            <div class=\"small text-uppercase fw-bold text-muted\">Enterprise</div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <span class=\"display-4 fw-bold\">$49</span>\r\n");
      out.write("                                <span class=\"text-muted\">/ mo.</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ul class=\"list-unstyled mb-4\">\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    <strong>Unlimited users</strong>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    5GB storage\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Unlimited public projects\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Community access\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Unlimited private projects\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Dedicated support\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"mb-2\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    <strong>Unlimited</strong>\r\n");
      out.write("                                    linked domains\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"text-muted\">\r\n");
      out.write("                                    <i class=\"bi bi-check text-primary\"></i>\r\n");
      out.write("                                    Monthly status reports\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class=\"d-grid\"><a class=\"btn btn-outline-primary\" href=\"#!\">Choose plan</a></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Testimonials section-->\r\n");
      out.write("    <section class=\"py-5 border-bottom\">\r\n");
      out.write("        <div class=\"container px-5 my-5 px-5\">\r\n");
      out.write("            <div class=\"text-center mb-5\">\r\n");
      out.write("                <h2 class=\"fw-bolder\">Customer testimonials</h2>\r\n");
      out.write("                <p class=\"lead mb-0\">Our customers love working with us</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row gx-5 justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <!-- Testimonial 1-->\r\n");
      out.write("                    <div class=\"card mb-4\">\r\n");
      out.write("                        <div class=\"card-body p-4\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <div class=\"flex-shrink-0\"><i class=\"bi bi-chat-right-quote-fill text-primary fs-1\"></i></div>\r\n");
      out.write("                                <div class=\"ms-4\">\r\n");
      out.write("                                    <p class=\"mb-1\">Thank you for putting together such a great product. We loved working with you and the whole team, and we will be recommending you to others!</p>\r\n");
      out.write("                                    <div class=\"small text-muted\">- Client Name, Location</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Testimonial 2-->\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-body p-4\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <div class=\"flex-shrink-0\"><i class=\"bi bi-chat-right-quote-fill text-primary fs-1\"></i></div>\r\n");
      out.write("                                <div class=\"ms-4\">\r\n");
      out.write("                                    <p class=\"mb-1\">The whole team was a huge help with putting things together for our company and brand. We will be hiring them again in the near future for additional work!</p>\r\n");
      out.write("                                    <div class=\"small text-muted\">- Client Name, Location</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Contact section-->\r\n");
      out.write("    <section class=\"bg-light py-5\">\r\n");
      out.write("        <div class=\"container px-5 my-5 px-5\">\r\n");
      out.write("            <div class=\"text-center mb-5\">\r\n");
      out.write("                <div class=\"feature bg-primary bg-gradient text-white rounded-3 mb-3\"><i class=\"bi bi-envelope\"></i></div>\r\n");
      out.write("                <h2 class=\"fw-bolder\">Get in touch</h2>\r\n");
      out.write("                <p class=\"lead mb-0\">We'd love to hear from you</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row gx-5 justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                    <!-- * * SB Forms Contact Form * *-->\r\n");
      out.write("                    <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                    <!-- This form is pre-integrated with SB Forms.-->\r\n");
      out.write("                    <!-- To make this form functional, sign up at-->\r\n");
      out.write("                    <!-- https://startbootstrap.com/solution/contact-forms-->\r\n");
      out.write("                    <!-- to get an API token!-->\r\n");
      out.write("                    <form id=\"contactForm\" data-sb-form-api-token=\"API_TOKEN\">\r\n");
      out.write("                        <!-- Name input-->\r\n");
      out.write("                        <div class=\"form-floating mb-3\">\r\n");
      out.write("                            <input class=\"form-control\" id=\"name\" type=\"text\" placeholder=\"Enter your name...\" data-sb-validations=\"required\" />\r\n");
      out.write("                            <label for=\"name\">Full name</label>\r\n");
      out.write("                            <div class=\"invalid-feedback\" data-sb-feedback=\"name:required\">A name is required.</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Email address input-->\r\n");
      out.write("                        <div class=\"form-floating mb-3\">\r\n");
      out.write("                            <input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"name@example.com\" data-sb-validations=\"required,email\" />\r\n");
      out.write("                            <label for=\"email\">Email address</label>\r\n");
      out.write("                            <div class=\"invalid-feedback\" data-sb-feedback=\"email:required\">An email is required.</div>\r\n");
      out.write("                            <div class=\"invalid-feedback\" data-sb-feedback=\"email:email\">Email is not valid.</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Phone number input-->\r\n");
      out.write("                        <div class=\"form-floating mb-3\">\r\n");
      out.write("                            <input class=\"form-control\" id=\"phone\" type=\"tel\" placeholder=\"(123) 456-7890\" data-sb-validations=\"required\" />\r\n");
      out.write("                            <label for=\"phone\">Phone number</label>\r\n");
      out.write("                            <div class=\"invalid-feedback\" data-sb-feedback=\"phone:required\">A phone number is required.</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Message input-->\r\n");
      out.write("                        <div class=\"form-floating mb-3\">\r\n");
      out.write("                            <textarea class=\"form-control\" id=\"message\" type=\"text\" placeholder=\"Enter your message here...\" style=\"height: 10rem\" data-sb-validations=\"required\"></textarea>\r\n");
      out.write("                            <label for=\"message\">Message</label>\r\n");
      out.write("                            <div class=\"invalid-feedback\" data-sb-feedback=\"message:required\">A message is required.</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Submit success message-->\r\n");
      out.write("                        <!---->\r\n");
      out.write("                        <!-- This is what your users will see when the form-->\r\n");
      out.write("                        <!-- has successfully submitted-->\r\n");
      out.write("                        <div class=\"d-none\" id=\"submitSuccessMessage\">\r\n");
      out.write("                            <div class=\"text-center mb-3\">\r\n");
      out.write("                                <div class=\"fw-bolder\">Form submission successful!</div>\r\n");
      out.write("                                To activate this form, sign up at\r\n");
      out.write("                                <br />\r\n");
      out.write("                                <a href=\"https://startbootstrap.com/solution/contact-forms\">https://startbootstrap.com/solution/contact-forms</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Submit error message-->\r\n");
      out.write("                        <!---->\r\n");
      out.write("                        <!-- This is what your users will see when there is-->\r\n");
      out.write("                        <!-- an error submitting the form-->\r\n");
      out.write("                        <div class=\"d-none\" id=\"submitErrorMessage\"><div class=\"text-center text-danger mb-3\">Error sending message!</div></div>\r\n");
      out.write("                        <!-- Submit Button-->\r\n");
      out.write("                        <div class=\"d-grid\"><button class=\"btn btn-primary btn-lg disabled\" id=\"submitButton\" type=\"submit\">Submit</button></div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    <!-- Optional JavaScript -->\r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"\r\n");
      out.write("        integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"\r\n");
      out.write("        integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"\r\n");
      out.write("        integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
